name: task-manager

services:
  mongo:
    image: mongo:8.0.4
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - task-manager

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - task-manager
    ports:
      - 7000:7000
    command: npm run dev -- --host
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./frontend/.env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - task-manager
    ports:
      - 5173:5173
    depends_on:
      - api

volumes:
  mongo_data:

networks:
  task-manager:
    driver: bridge
